config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recipes
  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  def self.filtered_by_ingredients(ingredient_list)
    if ingredient_list.present?
      query = ->(ingredient) { "array_to_string(ingredients, '||') ilike '%#{ingredient}%'" }

      result = Recipe.where(query.call(ingredient_list.first))
      ingredient_list.drop(1).map { |ingredient| result = result.where(query.call(ingredient)) }

      result
    else
      Recipe.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include Pagy::Backend

  def index
    @base_ingredients = YAML.load_file("#{Rails.root}/seed_data/base_ingredients.yml")
    @selected_ingredients = (params[:ingredients].present? ? params[:ingredients] : [])

    @pagy, @recipes = pagy(Recipe.filtered_by_ingredients(params[:ingredients])
                                 .order(ratings: :desc))
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Penny Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="app-container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/index.html.erb
<div class='main-wrapper'>
  <h1 class='page-title'>Find your recipe</h1>

  <%= form_for :ingredients, method: 'get', url: 'recipes', class:'ingredients-filter-form' do |form| %>
    <div class='ingredients-filter-container'>
      <% @base_ingredients.each do |ingredient| %>
        <label class='ingredient-select'>
          <%= check_box_tag "ingredients[]", ingredient, @selected_ingredients.include?(ingredient), id: ingredient %>
          <%= ingredient.capitalize() %>
        </label>
      <% end %>
    </div>

    <div class='ingredient-filter-controls'>
      <%= link_to 'Clear filters', root_path, class: 'ingredients-filter-reset button' %>
      <%= form.submit 'Filter recipes', class: 'ingredients-filter-submit button' %>
    </div>
  <% end %>

  <% if @recipes.exists? %>
    <div class='recipes-container'>
      <div class='recipes-links-container'>
          <% @recipes.each do |recipe| %>
            <%= link_to recipe_path(recipe), class: 'recipe-link' do %>
              <h2><%= recipe.title %></h2>
              <span><%= recipe.ratings %>/5</span>
            <% end %>
          <% end %>
      </div>
        <%== pagy_nav(@pagy) %>
    </div>
  <% else %>
    <p class='no-recipe-found'>No recipes found</p>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class='main-wrapper'>
  <%= link_to root_path do %>
    <div class='back-to-root-button button'>Back to home</div>
  <% end %>

  <h1 class='page-title'><%= @recipe.title %></h1>

  <div class='recipe-container'>
    <div class='infos-container'>
      <div class='info-container'>
        Author : <%= @recipe.author %>
      </div>
      <div class='info-container'>
        Prep time : <%= @recipe.prep_time %> minutes
      </div>
      <div class='info-container'>
        Cook time : <%= @recipe.cook_time %> minutes
      </div>
      <div class='info-container'>
        Ratings : <%= @recipe.ratings %>/5
      </div>
    </div>

    <div class='ingredients-container'>
      <h2 class='ingredients-title'>Ingredients</h2>
      <ul>
        <% @recipe.ingredients.each do |ingredient| %>
          <li><%= ingredient %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>